apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ec2-obs-otlp-testes-02-location
  description: Location to import all ec2-obs-otlp-testes-02 catalog components
spec:
  targets:
    - ./.platform/*.yaml
